version: "3"

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:

    image: infisical/infisical:latest-postgres
    platform: linux/amd64
    pull_policy: always
    env_file: .env
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - TLS_REJECT_UNAUTHORIZED=false
      - SMTP_TLS_REJECT_UNAUTHORIZED=false
      - REDIS_TLS_REJECT_UNAUTHORIZED=false
      - REDIS_TLS_ENABLED=true
      - TELEMETRY_ENABLED=false
      # 如果您有Redis CA证书，请取消注释下面这行并替换为实际的base64编码证书
      # - REDIS_TLS_CA_CERT=your-base64-encoded-ca-cert-here
      # 如果需要指定SNI服务器名，请取消注释下面这行并替换为实际的服务器名
      # - REDIS_TLS_SNI_SERVERNAME=your-redis-server-hostname
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - infisical
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infisical.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.infisical.entrypoints=websecure"
      - "traefik.http.routers.infisical.tls.certresolver=letsencrypt"
      - "traefik.http.services.infisical.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"

  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "6379"
    networks:
      - infisical
    volumes:
      - redis_data:/data

  # db:
  #   container_name: infisical-db
  #   image: postgres:14-alpine
  #   restart: always
  #   env_file: .env
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   networks:
  #     - infisical
  #   healthcheck:
  #     test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
  #     interval: 5s
  #     timeout: 10s
  #     retries: 10

volumes:
  redis_data:
    driver: local

networks:
  infisical:
    driver: bridge
  traefik:
    external: true
