api:
  dashboard: true
  insecure: true # 仅在开发环境使用，生产环境建议设置为false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@domain.com # 替换为您的邮箱
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: web

# 全局TLS配置
tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

# 日志配置
log:
  level: INFO

accessLog: {}

# 指标配置 (可选)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
